# Generated by Django 4.2.26 on 2025-11-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_qustion_text_question_question_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='testattempt',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='test',
            name='total_questions',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
    ]
